markdown: kramdown
safe: false
lsi: false
highlighter: rouge
permalink: /:categories/:year/:title/
url: https://brice-morin.info
author: Brice Morin
future: true
collections:
  breakout:
    output: true
